### ISSUE TITLE
some Errors

### ISSUE THREAD

**Issue by aslisk** [monosans/proxy-scraper-checker#11] opened 2022-03-11 12:59 UTC
![image](https://user-images.githubusercontent.com/28812980/157871046-0fff385b-9213-4ec5-8bf4-acae97f48a47.png)

**Comment by monosans** [comment] 2022-03-11 13:02
Duplicate of #4.

You can just ignore these errors.

I would also like to point out that this only happens on Windows.

**Closed by monosans** 2022-03-11 13:02 UTC
